// Mapa de sinonimos para deteccion de habilidades (100+ grupos)
export const SYNONYMS = {
  "javascript": ["js", "javascript", "ecmascript"],
  "js": ["js", "javascript", "ecmascript"],
  "typescript": ["ts", "typescript"],
  "ts": ["ts", "typescript"],
  "inteligencia artificial": ["ia", "inteligencia artificial", "artificial intelligence", "ai", "machine learning", "ml"],
  "ia": ["ia", "inteligencia artificial", "artificial intelligence", "ai"],
  "ai": ["ia", "inteligencia artificial", "artificial intelligence", "ai"],
  "machine learning": ["machine learning", "ml", "aprendizaje automatico", "deep learning", "dl"],
  "ml": ["machine learning", "ml", "aprendizaje automatico"],
  "python": ["python", "py"],
  "react": ["react", "reactjs", "react.js"],
  "node": ["node", "nodejs", "node.js"],
  "nodejs": ["node", "nodejs", "node.js"],
  "node.js": ["node", "nodejs", "node.js"],
  "css": ["css", "css3", "tailwind", "tailwindcss"],
  "html": ["html", "html5"],
  "automatizacion": ["automatizacion", "automation", "automatizar"],
  "api": ["api", "apis", "rest", "restful", "graphql"],
  "base de datos": ["base de datos", "sql", "postgresql", "mysql", "mongodb", "database"],
  "sql": ["sql", "postgresql", "mysql", "sqlite"],
  "aws": ["aws", "amazon web services", "cloud"],
  "gcp": ["gcp", "google cloud", "google cloud platform"],
  "azure": ["azure", "microsoft azure"],
  "docker": ["docker", "contenedores", "containers", "kubernetes", "k8s"],
  "figma": ["figma", "adobe xd", "sketch"],
  "ingles": ["ingles", "english", "idioma"],
  "liderazgo": ["liderazgo", "liderar", "lidere", "lider", "equipo", "gestion"],
  "scrum": ["scrum", "agile", "agil", "kanban", "metodologias agiles"],
  "testing": ["testing", "test", "jest", "cypress", "qa", "pruebas"],
  "git": ["git", "github", "gitlab", "version control"],
  "ci/cd": ["ci/cd", "cicd", "deploy", "deployment", "devops", "pipeline"],
  "prompt engineering": ["prompt engineering", "prompt", "prompting"],
  "make.com": ["make.com", "make", "integromat"],
  "n8n": ["n8n"],
  "zapier": ["zapier"],
  "hubspot": ["hubspot", "crm"],
  "tableau": ["tableau", "power bi", "powerbi", "visualizacion"],
  "tensorflow": ["tensorflow", "tf", "keras", "pytorch", "torch"],
  "langchain": ["langchain", "lang chain"],
  "claude": ["claude", "claude api", "anthropic"],
  "gpt": ["gpt", "gpt-4", "gpt-4o", "openai", "chatgpt"],
  "seo": ["seo", "sem", "posicionamiento", "search engine"],
  "google ads": ["google ads", "adwords", "sem", "ppc"],
  "meta ads": ["meta ads", "facebook ads", "instagram ads"],
};

// Mapa de nombres de display para habilidades
export const SKILLS_DISPLAY = {
  "react": "React", "node": "Node.js", "nodejs": "Node.js", "node.js": "Node.js",
  "python": "Python", "claude": "Claude API", "gpt": "GPT-4",
  "make.com": "Make.com", "n8n": "n8n", "zapier": "Zapier",
  "aws": "AWS", "docker": "Docker", "figma": "Figma", "langchain": "LangChain",
  "tensorflow": "TensorFlow", "hubspot": "HubSpot", "typescript": "TypeScript",
  "ts": "TypeScript", "javascript": "JavaScript", "js": "JavaScript",
  "sql": "SQL", "html": "HTML", "css": "CSS", "git": "Git",
  "ci/cd": "CI/CD", "testing": "Testing", "scrum": "Scrum/Agile",
  "seo": "SEO", "google ads": "Google Ads", "meta ads": "Meta Ads",
  "tableau": "Tableau/BI", "machine learning": "Machine Learning",
  "ml": "Machine Learning", "ia": "IA", "inteligencia artificial": "IA",
  "automatizacion": "Automatizacion", "api": "APIs", "liderazgo": "Liderazgo",
  "ingles": "Ingles", "prompt engineering": "Prompt Engineering",
  "base de datos": "Bases de datos", "azure": "Azure", "gcp": "GCP",
};
